In [1]:
import numpy as np

## creating array from list

In [2]:
zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
print(zeros)
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
full = np.full((4, 4), 4)
print(full)
print(np.full((4, 4), 4, dtype=np.float32))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [4]:
random = np.random.random((4,3))
print(random*1000000)
random2 = np.random.normal((2,2))
print(random2)
random3 = np.random.uniform((4,3))
print(random3)


[[507900.94330964 520655.53748847 320316.01818285]
 [264556.81626098 853744.32061037 375430.45989805]
 [647895.09409725 353837.78784623 555265.7780706 ]
 [746420.28766523 474606.74789998 410246.82212305]]
[0.87476899 2.51738388]
[3.6653874  2.03318337]


In [ ]:
sequence = np.arange(0, 10, 2)
print(sequence)
sequence2 = np.arange(0, 10, 0.5)
print(sequence2)


[0 2 4 6 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[ 0.   5.8 11.6 17.4 23.2 29.  34.8 40.6 46.4 52.2 58.  63.8 69.6 75.4
 81.2 87.  92.8 98.6]


In [6]:
list1 = [1, 2, 3, 4, 5]
print(list1 * 2)

list2 = np.array([1, 2, 3, 4, 5])
print(list2 * 2)

list3 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(list3 * 2)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [ ]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("Python list time:", time.time() - start)

start = time.time()
numpy_arr = np.array(np.arange(10000000)) * 2
print("Python numpy array time:", time.time() - start)



Python list time: 1.1930272579193115
Python numpy array time: 0.1699221134185791
