In [2]:
import numpy as np

## creating array from list

In [ ]:
zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
print(zeros)
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
full = np.full((4, 4), 4)
print(full)
print(np.full((4, 4), 4, dtype=np.float32))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [7]:
random = np.random.random((4,3))
print(random*1000000)
random2 = np.random.normal((2,2))
print(random2)
random3 = np.random.uniform((4,3))
print(random3)


[[130122.56684701 718677.30433855 887520.25471556]
 [870327.77254571 955961.93567392 839117.54091129]
 [312655.87657546 123391.96005441  42215.90198532]
 [ 24486.58425203 396892.5971207  131373.77738681]]
[2.07547639 3.16295056]
[1.90825407 2.66546813]


In [8]:
sequence = np.arange(0, 10, 2)
print(sequence)
sequence2 = np.arange(0, 10, 0.5)
print(sequence2)

[0 2 4 6 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
