In [1]:
import numpy as np

## creating array from list

In [2]:
zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
print(zeros)
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
full = np.full((4, 4), 4)
print(full)
print(np.full((4, 4), 4, dtype=np.float32))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [4]:
random = np.random.random((4,3))
print(random*1000000)
random2 = np.random.normal((2,2))
print(random2)
random3 = np.random.uniform((4,3))
print(random3)


[[833523.36655014 190691.07216017 647279.04767711]
 [523349.46894613 123996.95908634 226166.24892212]
 [614771.01061141 861978.20010018 764739.13713889]
 [475316.21818252 699031.85203618 481201.73169377]]
[0.59601206 1.49689955]
[1.18628921 1.72052392]


In [6]:
sequence = np.arange(0, 10, 2)
print(sequence)
sequence2 = np.arange(0, 10, 0.5)
print(sequence2)
sequence3 = np.arange(0, 100, 5.8)
print(sequence3)

[0 2 4 6 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[ 0.   5.8 11.6 17.4 23.2 29.  34.8 40.6 46.4 52.2 58.  63.8 69.6 75.4
 81.2 87.  92.8 98.6]
