In [2]:
import numpy as np

## creating array from list

In [3]:
zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
print(zeros)
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
full = np.full((4, 4), 4)
print(full)
print(np.full((4, 4), 4, dtype=np.float32))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [5]:
random = np.random.random((4,3))
print(random*1000000)
random2 = np.random.normal((2,2))
print(random2)
random3 = np.random.uniform((4,3))
print(random3)


[[108880.25115155 964409.19949734 680114.95212467]
 [686260.79878439 548730.74368234 333462.10696994]
 [271153.76766534 333476.38952392 440646.20495582]
 [512914.9817843  947863.14727917 125818.80507383]]
[0.58177017 2.7437253 ]
[1.07715175 2.76790056]


In [6]:
sequence = np.arange(0, 10, 2)
print(sequence)
sequence2 = np.arange(0, 10, 0.5)
print(sequence2)
sequence3 = np.arange(0, 100, 5.8)
print(sequence3)

[0 2 4 6 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[ 0.   5.8 11.6 17.4 23.2 29.  34.8 40.6 46.4 52.2 58.  63.8 69.6 75.4
 81.2 87.  92.8 98.6]


In [9]:
list1 = [1, 2, 3, 4, 5]
print(list1 * 2)

list2 = np.array([1, 2, 3, 4, 5])
print(list2 * 2)

list3 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(list3 * 2)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
