In [2]:
import numpy as np

## creating array from list

In [3]:
zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
print(zeros)
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
full = np.full((4, 4), 4)
print(full)
print(np.full((4, 4), 4, dtype=np.float32))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [15]:
random = np.random.random((4,3))
print(random*1000000)
random2 = np.random.normal((4,3))
print(random2)
random3 = np.random.uniform((4,3))
print(random3)

[[803395.37442681 827165.60995905 322696.71604325]
 [172014.49085545 682601.39642917 165754.62206014]
 [ 57933.03951488 598370.2527692  225175.22254061]
 [312354.50546734 398678.83922884  22656.82246733]]
[1.63663649 2.82962129]
[1.00296925 2.92150368]
